import jsPDF from "jspdf";

type StatementData = {
  expertName: string;
  levelName: string;
  periodLabel: string;
  cutoffDate: string;
  amount: number;
  currency: string;
  status: string;
  transactionReference: string | null;
  payoutMethod: string;
  maskedAccount: string;
  projects: { title: string; earnings: number; sharePct: number | null }[];
};

export function generatePayoutStatementPDF(data: StatementData) {
  const doc = new jsPDF();
  let y = 20;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("Eduxellence Expert Payout Statement", 20, y);
  y += 12;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);

  const line = (label: string, value: string) => {
    doc.setFont("helvetica", "bold");
    doc.text(label, 20, y);
    doc.setFont("helvetica", "normal");
    doc.text(value, 80, y);
    y += 7;
  };

  line("Payment Period:", data.periodLabel);
  line("Cutoff Date:", new Date(data.cutoffDate).toLocaleDateString());
  line("Expert:", data.expertName);
  line("Level:", data.levelName);
  line("Payment Method:", data.payoutMethod);
  line("Destination Account:", data.maskedAccount);
  y += 3;
  line("Gross Eligible Earnings:", `${data.amount.toFixed(2)} ${data.currency}`);
  line("Adjustments:", `0.00 ${data.currency}`);
  line("Amount Paid:", `${data.amount.toFixed(2)} ${data.currency}`);
  line("Status:", data.status);
  line("Transaction Reference:", data.transactionReference || "—");

  y += 8;
  doc.setFont("helvetica", "bold");
  doc.text("Projects in this Payout:", 20, y);
  y += 7;
  doc.setFont("helvetica", "normal");

  data.projects.forEach((p) => {
    doc.text(`${p.title} — ${p.earnings.toFixed(2)} ${data.currency}${p.sharePct ? ` (${Math.round(p.sharePct * 100)}% share)` : ""}`, 24, y);
    y += 6;
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
  });

  y += 10;
  doc.setFontSize(8);
  doc.setTextColor(120);
  doc.text("This statement is generated by Eduxellence Solutions Bright Horizon for record-keeping purposes.", 20, y);

  doc.save(`Eduxellence-Payout-Statement-${data.periodLabel.replace(/\s+/g, "-")}.pdf`);
}